package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Monday, April 28, 2025 10:37:53 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
  String uppercase (String str);
} // interface ReverseOperations
