package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Friday, April 25, 2025 7:13:49 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
